export type VendorRow = {
  fullName: string;
  email: string;
  phoneNumber: string;
  businessName: string;
  storeType: string;
  businessAddress: string;
  latitude: number | null;
  longitude: number | null;
  productCategory: string;
  socials: string | null;
  vendorId: string;
  bankName: string;
  bankCode: string;
  accountNumber: string;
  accountName: string;
  returnPolicy: string;
  deliveryDuration: string;
  updatedAt: string;
  createdAt: string;
};

export type VendorInsert = {
  vendor_id: string;
  full_name: string;
  email: string;
  phone_number: string;
  business_name: string;
  store_type: string;
  business_address: string;
  latitude: number | null;
  longitude: number | null;
  product_category: string;
  socials: string | null;
  bank_name: string;
  bank_code: string;
  account_number: string;
  account_name: string;
  return_policy: string;
  delivery_duration: string;
  subaccount_code: string | null;
  subaccount_pending: boolean;
  updated_at: string;
};
