export type VendorRow = {
  id: string;
  fullName: string;
  email: string;
  phoneNumber: string;
  businessName: string;
  storeType: string;
  businessAddress: string;
  latitude: number | null;
  longitude: number | null;
  productCategory: string;
  socials: string | null;
  vendor_id: string;
  bankName: string;
  bankCode: string;
  accountNumber: string;
  accountName: string;
  returnPolicy: string;
  deliveryDuration: string;
  subaccount_code: string | null;
  subaccount_pending: boolean;
  updatedAt: string;
  createdAt: string;
};

export type VendorInsert = {
  vendor_id: string | undefined;
  full_name: string;
  email: string;
  phone_number: string;
  business_name: string;
  store_type: string;
  business_address: string;
  latitude: number | null;
  longitude: number | null;
  product_category: string;
  socials: string | null;
  bank_name: string;
  bank_code: string;
  account_number: string;
  account_name: string;
  return_policy: string;
  delivery_duration: string;
  subaccount_code: string | null;
  subaccount_pending: boolean;
  updated_at: string;
};

export interface Vendor {
  id: string;
  business_name?: string;
  full_name: string;
  product_category?: string;
  business_address?: string;
  phone_number?: string;
  email?: string;
  socials?: string;
  logo_url?: string;
  cover_url?: string;
  verified?: boolean;
  joined_at?: string;
  total_products?: number;
  average_rating?: number;
  instagram?: string;
  facebook?: string;
  x?: string;
  tiktok?: string;
  website?: string;
  active?: boolean;
}
